send_raw_command:
  name: Send raw command
  description: Sends a raw text command to the targeted VoiceMeeter device
  target:
    device:
      integration: vban
  fields:
    command:
      name: Command
      description: The raw command string
      required: true
      example: "Strip[0].Mute=1;"
      selector:
        text:

set_gain:
  name: Set gain
  description: Set gain for a specific strip or bus number entity
  target:
    entity:
      integration: vban
      domain:
        - number
  fields:
    gain:
      name: Gain
      description: Gain in dB
      required: true
      example: -10.5
      selector:
        number:
          min: -60
          max: 12
          step: 0.1
          unit_of_measurement: dB
          mode: box

set_mute:
  name: Set mute
  description: Set mute state for a specific strip or bus switch entity
  target:
    entity:
      integration: vban
      domain:
        - switch
  fields:
    mute:
      name: Mute
      description: True to mute, False to unmute
      required: true
      example: true
      selector:
        boolean:
