send_raw_command:
  target:
    device:
      integration: vban
  fields:
    command:
      required: true
      example: "Strip[0].Mute=1;"
      selector:
        text:

set_gain:
  target:
    entity:
      integration: vban
      domain:
        - number
  fields:
    gain:
      required: true
      example: -10.5
      selector:
        number:
          min: -60
          max: 12
          step: 0.1
          unit_of_measurement: dB
          mode: box

set_mute:
  target:
    entity:
      integration: vban
      domain:
        - switch
  fields:
    mute:
      required: true
      example: true
      selector:
        boolean:
